### PR TITLE
[Please help me get the YOLO Github Badge] Add the doc for XKJD

### PR DESCRIPTION
**Pull request by pingshunhuangalex**
Hi @ayaka14732 

I'm trying to get the `YOLO` Github badge via this PR.

If you don't mind, could you please merge this PR **WITHOUT** approving it? Thanks heaps.

### CODE REVIEW

**Comment by pingshunhuangalex** [comment]
To clarify, could you please

- Add yourself as the reviewer
- Merge the PR without approving it (code review).

Thanks!

**Comment by ayaka14732** [comment]
Sorry but the link should be a GitHub repository, so it cannot be GitBook. Otherwise the script for updating stars will not work.

**Comment by pingshunhuangalex** [comment]
The repo link is a Github. I just add the doc link in the description, or maybe I should just write out the link as text cuz I saw a similar example below somewhere.

**Comment by ayaka14732** [comment]
Can you try to revert your changes, so that it become an empty PR, and I can try to merge it without approving?

**Comment by pingshunhuangalex** [comment]
I changed the link to plain text. Does it work this way cuz we have link text in other items too?

**Pull request merged**
